name: CI

on:
  push:
    branches: [ "main", "3.2.x-new" ]
  pull_request:
    branches: [ "main", "3.2.x-new" ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
        cache: 'sbt'
    - name: Build and Test Scalactic and ScalaTest using Scala 2.13
      run: sbt test
    - name: Build and Test ScalaTest using Scala 3
      run: sbt scalatestTestDotty/test
    - name: Build and Test Scalactic using Scala 3
      run: sbt scalacticTestDotty/test
    - name: Build and Test ScalaTest-JS using Scala 3
      run: sbt scalatestTestJS/test
    - name: Build and Test Scalactic-JS using Scala 3
      run: sbt scalacticTestJS/test         